---
input_file: ./README.md
output_directory: ./slides
output_filename: index
reveal:
  template:
  template_color: FFFFFF
  intro:
  intro_title: Your Fancy Title
  intro_author: Chad Peterson
  intro_color: 049FD9
  closing:
  closing_message: Thank you!
  closing_color: 049FD9
